ccflags-$(CONFIG_INPUT_FINGERPRINT_FPC1542) += -I$(srctree)/drivers/misc/mediatek/teei/400/tz_driver/include/
ccflags-$(CONFIG_INPUT_FINGERPRINT_FPC1542) += -I$(srctree)/drivers/misc/mediatek/teei/400/common/include/
obj-$(CONFIG_INPUT_FINGERPRINT_FPC1542) += mtk_spi.o
